name: 'Notify docs about submodule changes'

on:
  push:
    branches:
      - main
    paths: [ README.md ]

  workflow_dispatch:

jobs:
  notify:
    name: 'Notify docs about submodule changes'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Github REST API Call
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        PARENT_REPO: AnastasiaTWW/test-docs
        PARENT_BRANCH: master
        WORKFLOW_ID: 11467734
      run: |
        curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
